### ISSUE TITLE
Thanks for finding my old code.

### ISSUE THREAD

**Issue by kenjihiranabe** [kenjihiranabe/javax.vecmath#2]
I just wanted to say thank you for finding my old code and made it public here in github. If you want to change the license type or there is anything I can do, please let me know.
-Kenji Hiranabe

**Comment by porst17** [comment]
Dear Kenji Hiranabe,

sorry for my late reply. I was very glad to find your code online. We had some issues with the license of the vecmath library of Oracle. I also created a maven repository for your code (binary + source) at https://github.com/IMAGINARY/maven-repository and we are planning to use it in some of our projects (see e.g. http://imaginary.org/program/surfer/). Internally, I already switch to your implementation, but it is not yet online.

Thanks a lot!

**Comment by kenjihiranabe** [comment]
Great!
Hope your project goes well.
-Kenji
