### ISSUE TITLE
Migrate repository to kenjihiranabe

### ISSUE THREAD

**Issue by porst17** [kenjihiranabe/javax.vecmath#3]
@kenjihiranabe

Since you are the original author, I am thinking if it would be better to transfer the ownership of this repository to your account. I.e. you would become the maintainer (of your original code) again. This would also give you proper attributation for your work.

What do you think?

I would fork the repo back to my account after transfering for making my own changes.

**Comment by kenjihiranabe** [comment]
Thanks.
Is that "transfer ownership" operation easy for me to do ?
I'm away from programming for sometime, and to create a build environment
is not easy.
If you can do the transfer with web only (non-programming env involved), I
think I can.

Best,

-Kenji

---

"There are no original ideas. There are only original people."
Kenji Hiranabe, co-founder CEO, astah.net

2014-09-01 15:12 GMT+09:00 Christian Stussak notifications@github.com:

**Comment by porst17** [comment]
It can be done via the GitHub web interface by me. GitHub will send you a confirmation email.

Setting up a build enviroment is not easy in general and that's one of the reasons I use gradle as a build tool today. For good reason this tool became so popular recently. The only thing you need is a working Java Development Kit. Everything else can be done via pretty easy command line stuff (pulling in dependencies, building, deploying, publishing etc).

So, if you are willing to take over ownership, just let me know and I will initiate the process.

**Comment by kenjihiranabe** [comment]
Yes, I'm willing!
Is the version you first imported the one on
http://objectclub.jp/download/vecmath_e ?
(I suspect so)

-Kenji

---

"There are no original ideas. There are only original people."
Kenji Hiranabe, co-founder CEO, astah.net

2014-09-01 17:32 GMT+09:00 Christian Stussak notifications@github.com:

**Comment by porst17** [comment]
Transferring ownership worked fine. No problems at all.

**Comment by kenjihiranabe** [comment]
Great, Thanks Christian!
-Kenji

---

"There are no original ideas. There are only original people."
Kenji Hiranabe, co-founder CEO, astah.net

2014-09-02 16:37 GMT+09:00 Christian Stussak notifications@github.com:
