### ISSUE TITLE
Implement javax.vecmath 1.5.2 specification

### ISSUE THREAD

**Issue by porst17** [kenjihiranabe/javax.vecmath#4]
@kenjihiranabe

The current implementation is for the 1.2.x specification of `javax.vecmath`. I would be great to implement the full (most recent) 1.5.2 specification and give the result back to the community under an open license (maybe a bit more specific than your current license, e.g. something like BSD 3-clause or Apache v2). Since it doesn't seem that `javax.vecmath` is developed any further, this would also mean that the implementation would be kind of _complete_. 

Is there any record of the differences between `javax.vecmath` versions 1.2.x and 1.5.x available to the public?

Would you be willing to contribute in the development?

**Comment by kenjihiranabe** [comment]
That would be great!
I have another C++ port version, too, which is I think more popular.
http://objectclub.jp/download/vecmath_e

Kenji

---

"There are no original ideas. There are only original people."
Kenji Hiranabe, co-founder CEO, astah.net

2014-09-01 15:18 GMT+09:00 Christian Stussak notifications@github.com:

**Comment by porst17** [comment]
Regarding the C++ port: It seems reasonable, that this port is more popular than the Java version since for Java, there is still Sun's implementation with the only limitation being the license issue for some people (like me).

Would you like to contribute to the extension of the code to 1.5.2?

**Comment by kenjihiranabe** [comment]
Christian,
Yes, I can comment, advice, review, write some corrections to be pulled.
-Kenji

---

"There are no original ideas. There are only original people."
Kenji Hiranabe, co-founder CEO, astah.net

2014-09-01 17:40 GMT+09:00 Christian Stussak notifications@github.com:

**Comment by porst17** [comment]
Ok, great, I will let you know as soon as I start (may take a while).

**Comment by porst17** [comment]
I don't see this happen any time soon, so I will close it as `wontfix`.
